name = "add-magnet-link"
main = "index.js"
compatibility_date = "2023-12-01"
account_id = ""

# routes = [ { pattern = "add.your.domain.dev", custom_domain = true } ]

[vars]
API_BASE_URL = ""
SECRET_KEY = ""
# optional:
# only set if using Cloudflare Access to protect worker
# API_USERNAME = ""
# API_PASSWORD = ""